@hostname = [::1]
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
### Request
GET http://{{host}}/api/foo
### Response

GET http://{{host}}/api/auth/login
### Response

GET http://{{host}}/api/auth/1
### Response